### ISSUE TITLE
Package recipes not working

### ISSUE THREAD

**Issue by bhankas** [marienz/nix-doom-emacs-unstraightened#20]
First, amazing job! Thanks a lot for working on this!

I have a few packages that are not in ELPA/MELPA/emacs-overlay, and they are all added in `packages.el` via recipe as mentioned below:

```emacs-lisp
 (package! org-footnote-assistant
   :recipe (:type git :host github :repo "lazzalazza/org-footnote-assistant"))

 (package! hledger-input
   :recipe (:type git
            :host github
            :repo "narendraj9/hledger-mode"))

 (package! nix3
   :recipe (:type git :host github :repo "emacs-twist/nix3.el"))

 (package! gleam-ts-mode
   :recipe (:type git
            :host github
            :repo "gleam-lang/gleam-mode"
            :branch "gleam-ts-mode"
            :files ("gleam-ts-mode.el")))
```

None of these work, with very similar error:

```
error: nix3: not in epkgs, not elpa, no recipe or not pinned
```

I feel like I'm missing something obvious, so forgive me for being dumb.

Thanks again, this is really great!

**Comment by bhankas** [comment]
Nevermind, I am dumb. It says right there that recipes need to be pinned, which makes sense with this being Nix-land.. Everything worked after adding a `:pin` to recipes.

**Comment by marienz** [comment]
Glad you like it!

That error message is... not great (it's from an assert that hasn't really changed from when I started working on this).

I've split up the check for "can't figure out repository URL" and "need a pin" and improved both error messages, so you'll get:

```
       error: nix-doom-emacs-unstraightened: nix3: not in nixpkgs or emacs-overlay, not pinned.
       All packages must be pinned so they can be fetched deterministically.

       If this is a custom `package!` entry in your packages.el, add a `:pin`.
       If it is a `package!` in Doom, add an entry to Unstraightened's fetch-overrides.nix.
```

which should make it a bit more obvious what the problem is.

And yeah, with that check removed you'd get

```
       error: in pure evaluation mode, 'fetchGit' will not fetch unlocked input 'git+https://github.com/emacs-twist/nix3.el?exportIgnore=1'
```

I think it'd technically work without flakes... but I think it's reasonable to just enforce determinism here, and for flakes users having the name of the package triggering this in the error message seems more useful than the URL.
