### ISSUE TITLE
ob-ammonite: not in epkgs, not elpa, no recipe or not pinned

### ISSUE THREAD

**Issue by leifhelm** [marienz/nix-doom-emacs-unstraightened#3]
I tried to use your package with org mode and scala enabled. The following error occured
```
ob-ammonite: not in epkgs, not elpa, no recipe or not pinned
```
but it is pinned in `modules/lang/org/packages.el`
```elisp
(package! ob-ammonite :pin "39937dff395e70aff76a4224fa49cf2ec6c57cca"))
```

**Comment by marienz** [comment]
Thanks for flagging!

I initially misread your report and found a different bug (filed as #4), triggered by enabling scala with org. Need to fix that later: probably not as common a problem (and can be worked around by either enabling the org module or disabling the org package).

I didn't notice this problem myself for the same reason the readme mentions "not all Doom module flags may work": basically all modules are covered individually, but modules that pull in additional packages if some other module is enabled aren't tested yet. I think I know how to fix this (walk all `packages.el` files and extract flags, more or less).

The underlying problem is two more packages from emacsattic, which isn't in emacs-overlay. The error message doesn't make that clear, I'll tweak that later. Once all modules and flags are properly tested, that may uncover a few more, but assuming emacsattic packages don't usually migrate back out of the attic just adding pins for them shouldn't be too bad.

It did uncover one more subtle problem: dependencies on packages neither in emacs-overlay nor explicitly depended upon or pinned by Doom weren't working.

Merging fix momentarily (which I build-tested locally)...

**Comment by marienz** [comment]
@leifhelm can you please confirm this fixes it for you? I build-tested this but I don't use scala so can't quickly test it beyond that.

**Comment by leifhelm** [comment]
Thank you for fixing this so quickly. It works now.
