### ISSUE TITLE
doom-intermediates build failure wrong type argument (hash-table-p nil)

### ISSUE THREAD

**Issue by timhae** [marienz/nix-doom-emacs-unstraightened#34]
I face this error
```
x There was an unexpected runtime error
  Message: Wrong type argument
  Details: (hash-table-p nil)
  Backtrace:
    (gethash (:completion . company) nil)
    (and t (gethash key doom-modules))
    (let* ((m (and t (gethash key doom-modules)))) (if m (if property (aref ...
    (doom-module-get (:completion . company) :path)
    (and t (doom-module-get key :path))
    (let* ((path (and t (doom-module-get key :path)))) (if path (if file (fi...
    (doom-module-expand-path (:completion . company) nil)
    (and t (doom-module-expand-path key file))
    (let* ((path (and t (doom-module-expand-path key file)))) (if path (if (...
    (let (file-name-handler-alist) (let* ((path (and t (doom-module-expand-p...
    (doom-module-locate-path (:completion . company))
    (funcall fn (cons group module) :flags (if (listp m) (cdr m)) :path (doo...
x There was an unexpected runtime error
  Message: File is missing
  Details: ("Searching for program" "No such file or directory" "git")
  Backtrace:
    (signal file-missing ("Searching for program" "No such file or directory...
    (if (not (and path (featurep 'doom))) (signal (car e) (cdr e)) (cl-loop ...
    (condition-case e (load path noerror 'nomessage) ((debug doom-error) (si...
    (doom-load "/nix/store/xvbddaaii0w6yhbkqxr7q0j905zkasbl-doomdir/init.el" t)
    (let ((output-directory (cdr (assq 'output-directory alist)))) (doom-loa...
    ((closure (t) (cli alist) (let ((output-directory (cdr (assq 'output-dir...
    (funcall (closure (t) (cli alist) (let ((output-directory (cdr (assq 'ou...
    (doom-cli-execute #s(doom-cli ("dump") nil (("SUMMARY" . "Dump intermedi...
    (let ((cli x21) (bindings x22)) (doom-cli-execute cli bindings))
    (let* ((x21 (car-safe x20)) (x22 (cdr-safe x20))) (let ((cli x21) (bindi...
    (progn (ignore (consp x20)) (let* ((x21 (car-safe x20)) (x22 (cdr-safe x...
    (let ((x20 (car tail))) (progn (ignore (consp x20)) (let* ((x21 (car-saf...
Searching for program: No such file or directory, git
```
with the default doomdir in the repo and the following diff to the flake lock:
```
diff --git a/flake.lock b/flake.lock
index 01b3002..1f2dd20 100644
--- a/flake.lock
+++ b/flake.lock
@@ -3,11 +3,11 @@
     "doomemacs": {
       "flake": false,
       "locked": {
-        "lastModified": 1727936788,
-        "narHash": "sha256-bIXSqOlmJL/PZUou2dx7Lj2wDkF98V9XiVsP1ffnbaw=",
+        "lastModified": 1729406511,
+        "narHash": "sha256-hTJId3fwetRJFGF5OLh2cYXicjPduKT/UcBXdDjsbPE=",
         "owner": "doomemacs",
         "repo": "doomemacs",
-        "rev": "8b9168de6e6a9cabf13d1c92558e2ef71aa37a72",
+        "rev": "fafdb25dd8a6ecd21ba82ffc0e92be3816d063ba",
         "type": "github"
       },
       "original": {
@@ -23,11 +23,11 @@
         "nixpkgs-stable": []
       },
       "locked": {
-        "lastModified": 1728721118,
-        "narHash": "sha256-A/FIm25BDJzubQcHkjIdqC56IblFtn1UWtCtmrEm75o=",
+        "lastModified": 1729530678,
+        "narHash": "sha256-Jwhm4pV8YtrKO7rU6cEgbqsaU/6dP2qLjO33pl/Wodk=",
         "owner": "nix-community",
         "repo": "emacs-overlay",
-        "rev": "e3634be032a23ea92c871afc57dc748d2c46623d",
+        "rev": "6025acb8c873345197aae8cf9ff06cf11c61d5f8",
         "type": "github"
       },
       "original": {
@@ -56,12 +56,11 @@
     },
     "nixpkgs": {
       "locked": {
-        "lastModified": 1728538411,
-        "narHash": "sha256-f0SBJz1eZ2yOuKUr5CA9BHULGXVSn6miBuUWdTyhUhU=",
-        "owner": "NixOS",
-        "repo": "nixpkgs",
-        "rev": "b69de56fac8c2b6f8fd27f2eca01dcda8e0a4221",
-        "type": "github"
+        "lastModified": 1728018373,
+        "narHash": "sha256-NOiTvBbRLIOe5F6RbHaAh6++BNjsb149fGZd1T4+KBg=",
+        "path": "/nix/store/sdzpqjwx7pdx6lsq6llyfqqf7hspp83c-source",
+        "rev": "bc947f541ae55e999ffdb4013441347d83b00feb",
+        "type": "path"
       },
       "original": {
         "id": "nixpkgs",
```
How can I resolve that issue? for me it is really hard to figure out where this is comming from originally and the
```
       >   Message: File is missing
       >   Details: ("Searching for program" "No such file or directory" "git")
```
added to that confusion. In the end I just would like to update my flake lock from time to time, do you have a good strategy on how to do that without breaking the package?

**Comment by marienz** [comment]
I encourage you to update the Unstraightened flake itself, then (optionally) update the `nixpkgs` input, but leave the `doomemacs` and `emacs-overlay` input alone. If you use Unstraightened as an input in some other flake, that means "maybe set `nix-doom-emacs-unstraightened.inputs.nixpkgs.follows = "nixpkgs"` but leave `nix-doom-emacs-unstraightened-inputs.doomemacs` (and `emacs-overlay`) alone". If you build from the Unstraightened flake, that means "run `git pull`, optionally run `nix flake update nixpkgs`, don't run `nix flake update` (which updates all inputs)".

Normally, the `emacs-overlay` and `doomemacs` inputs in the `unstraightened` repo update automatically every 24 hours. Currently they're a bit behind: initially because of an incompatible change to `factor/fuel` (see https://github.com/doomemacs/doomemacs/pull/8115, it broke Unstraightened more than it broke Doom), now because of an incompatible change to Doom I need to adjust Unstraightened to support (see https://github.com/doomemacs/doomemacs/commit/15904349cfb1fb920a0b275850859dda701186bc) and one other issue I haven't tracked down yet. I currently believe you're hitting the second one of these.

Unfortunately because of the way `unstraightened` works if you just blindly update the emacs-overlay and/or doomemacs inputs things will occasionally break (usually not as long as they have here, it was a bit of a perfect storm of unrelated breakages and me being busy...). If you stick to the revisions that passed CI you shouldn't have any issues, and if CI fails I'm generally already aware (I get notified of the GitHub action failures). I haven't been filing tracking issues for those CI failures, so it makes sense this caught you unaware.

I'll repurpose this issue to track fixing that "wrong type argument" error (assuming it's the same one I think I've seen once updated past that `factor/fuel` issue...), but please let me know if the above didn't answer your question about updating.

I'd also greatly appreciate suggestions on how to document all this. Because Nix gives you multiple ways of consuming/using Unstraightened, I find it difficult to document the answer to questions like yours (there is no one specific answer...). The "Note" below https://github.com/marienz/nix-doom-emacs-unstraightened/?tab=readme-ov-file#test-run was trying to answer your question, but it sounds like that did not work.

**Comment by timhae** [comment]
Thanks a lot, I must have missed that part of the readme, sorry. So I just ended up going for the "update unstraightened and remove emacs-overlay and doom from my flake inputs" and it works :) leaving this open for you to track the update but my issue is resolved :)

**Comment by marienz** [comment]
Glad to hear it!

I've now fixed the "one other issue I haven't tracked down yet" (nixpkgs got stricter about byte-compilation failures, uncovering two problems that previously went undetected). emacs-overlay and nixpkgs inputs are back up-to-date, doomemacs is still behind that breaking change that will take me a little longer to wrap my head around.

**Comment by marienz** [comment]
CI passes again, with https://github.com/marienz/nix-doom-emacs-unstraightened/commit/de2c546f74b699e0bfcb3ddae2983af2adeb09af fixing the error from this issue's title.
