### ISSUE TITLE
Literate config does not work

### ISSUE THREAD

**Issue by ArthurHeymans** [marienz/nix-doom-emacs-unstraightened#35]
[literate config](https://github.com/doomemacs/doomemacs/tree/master/modules/config/literate) does not work for me.

The package.el and config.el are not generated based on my config.org file.

**Comment by marienz** [comment]
I'm a bit confused by that feature: if I understand it correctly it runs early in `doom sync`, presumably before packages.el is read (or you wouldn't be able to use it to generate packages.el), which'd mean it uses the org-mode bundled with Emacs instead of the one specified by Doom's modules/lang/org/packages.el...

If that is how it works, it may take a bit of tinkering to support something similar. My first idea was to add something to `build-doom-profile.sh`, but that wouldn't work for packages.el (we read that much earlier). My second idea is to add support for running `doom +org tangle` (assuming that works without dependencies installed) very early (before building Emacs packages), which would work for not just packages.el but also init.el.

This will take a bit of experimentation... I can't just use / trigger that literate config module, it's tied to `doom sync`, which we don't have an exact equivalent of.

**Comment by ArthurHeymans** [comment]
Alright, thanks for looking into this!

**Comment by marienz** [comment]
I've pushed a possible fix for this to a branch. Can you please test it (and let me know if it's similar enough to `:config literate` to not need further documentation)?

To do so, assuming you're using home-manager, your `config.org` is in the root of your `doomDir`, and it contains blocks like `#+begin_src emacs-lisp :tangle config.el`:
- Switch to the `tangle` branch (`nix-doom-emacs-unstraightened.url = "github:marienz/nix-doom-emacs-unstraightened/tangle";` in flake.nix)
- Add `tangleArgs = '.';` to the `programs.doom-emacs` home-manager configuration

(If your tangle blocks look different and/or there are other .org files that should not be processed you'll need more elaborate `tangleArgs`, I'm hoping `doom +org tangle --help` is sufficient documentation...)

This currently uses the version of org-mode that comes with Emacs when tangling (not the one Doom uses at runtime). I'm assuming org-mode is stable enough this will generally work: please let me know if this is a misunderstanding.

**Comment by ArthurHeymans** [comment]
This works well for me. Thanks!

**Comment by marienz** [comment]
Thanks for testing!

I'll push the changes to main soon, hopefully... CI is failing for reasons I don't understand (see https://github.com/marienz/nix-doom-emacs-unstraightened/issues/42) which I'll have to do something about first.

**Comment by marienz** [comment]
Pushed (...and I referenced the wrong issue in the commit above, that should've been #41)
