### ISSUE TITLE
org-roam enabled with (org +roam2) has known `Wrong type argument: integer-or-marker-p` during linking

### ISSUE THREAD

**Issue by RafalBabinicz** [marienz/nix-doom-emacs-unstraightened#44]
While using org-roam (v2) any notes that use links between note result in known
error `Wrong type argument: integer-or-marker-p`.
It could be related to how unstraightened compiles elisp files of org and org-roam.

https://github.com/org-roam/org-roam/issues/2361

Step to reproduce:
use `org-roam-node-insert` function in any existing node to insert link to another node to trigger it.
E.g org-roam with only this two files
at org/roam/20241205235901-test_roam.org
```org
:PROPERTIES:
:ID:       f496571c-2bcf-41de-a891-c582c11f391a
:END:
#+title: Test roam
```
at org/roam/20241205235916-test_roam_with_link.org
```org
:PROPERTIES:
:ID:       8a3e4654-7425-4c1c-a137-0e90ef3d72a7
:END:
#+title: Test roam with link
[[id:f496571c-2bcf-41de-a891-c582c11f391a][Test roam]]
```
makes latter file invisible in org-roam and gives error
`⛔ Error (org-roam): Failed to process /home/user/org/roam/20241205235956-link_test.org with error Wrong type argument: integer-or-marker-p, nil, skipping...`

**Comment by marienz** [comment]
...hmm, this might be a bit tricky. Thanks for pointing towards that upstream issue: it's possible it's a variant of that (in which case it might be breaking more packages depending on org but probably not more than that, for reasons described below).

Any chance you can explain how to reproduce this in enough detail I can follow along without knowing how org-roam works? Starting from `nix run .#doom-emacs` (with `:lang (org +roam2)` enabled), what keys do I press / commands do I run to get that error message?

Notes (feel free to skip, they're me thinking out loud):

I wanted to say "Nix is immune to stale bytecode by design" (because if a dependency changes downstream derivations are rebuilt from scratch), but that may not be true here: Emacs bundles org, so it is possible for packages like org-roam to use the version bundled with Emacs at byte-compilation time and then use the version Doom pulls in at runtime.

org-roam does depend on org properly, looks like (emacs-org-9999snapshot is in buildInputs). But our org-mode derivation is one of the handful of non-(m)elpa ones: if (m)elpa2nix-build-package isn't finding / activating it...

...byte compilation is done using [elpa2nix](https://github.com/NixOS/nixpkgs/blob/c77b49d099d059c95da2f39fc06fb3210be9f839/pkgs/applications/editors/emacs/build-support/elpa2nix.el#L4), which calls into packages.el, which "activates" it and its dependencies before byte-compiling it. If that's able to activate (add to load-path) packages with proper metadata but not our org package, that'd do it...

...yeah, there's a /nix/store/ynvq6qz942igzfkwzx076pkpd2bw31jw-emacs-org-9999snapshot/nix-support/setup-hook that looks like it should put our share/emacs/site-lisp on load-path, but we're in an `org` subdirectory below that. I'd expect the same mechanism to be sufficient for packages.el to be able to activate the "normal" packages. But looks like org gets added to load-path by subdirs.el written by emacsWithPackages, which won't help us at build time.

...in which case converting [our org-mode derivation](https://github.com/marienz/nix-doom-emacs-unstraightened/blob/688d42c797b5359a5a4cb276e100139cb6d192b9/elisp-packages.nix#L59-L92) from a `trivialBuild` to a `melpaBuild` might fix it.

It looks like upstream (nixpkgs and emacs-overlay) don't use trivialBuild for any actual packages, and although I use it for a few of them everything except org is probably a "leaf" (no dependents)  package. So I should see if I can stop using it but if this is the problem packages building on org are likely the only broken ones.

**Comment by marienz** [comment]
Reproduced what I think is the same error (by creating the files as you described them in my homedir and running org-roam-db-sync (SPC n r s).

Now I just have to figure out how to fix it...

**Comment by marienz** [comment]
Ok, that *probably* fixed it, so I pushed it.

Can you please test?

**Comment by RafalBabinicz** [comment]
Tested. Imported my hole roam db with no issues. Linking works. No errors or warnings.
