### ISSUE TITLE
zen module fails to install due to missing commit that is available in emacs-overlay melpa

### ISSUE THREAD

**Issue by RafalBabinicz** [marienz/nix-doom-emacs-unstraightened#46]
After enabling `zen` module, I get following error during nixos-rebuild switch:
```
 error: Cannot find Git revision '519e05f74825abf04b7d2e0e38ec040d013a125a' in ref 'master' of repository 'https://gitlab.com/jabranham/mixed-pitch.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```

The thing is `mixed-pitch` package is old with the latest commit being 3yo 519e05f74825abf04b7d2e0e38ec040d013a125a

According to readme I should try to pin emacs-overlay to be closer to doomemacs,
but after checking emacs-overlay melpa json:
```json
{
  "ename": "mixed-pitch",
  "commit": "7d3c7af03e0bca3f834c32827cbcca29e29ef4db",
  "sha256": "1gda4jl946qlbf8rqm0mk493kwy8yqldr21cr583l6b6gl1nb4qf",
  "fetcher": "gitlab",
  "repo": "jabranham/mixed-pitch",
  "unstable": {
   "version": [
    20210304,
    1900
   ],
   "commit": "519e05f74825abf04b7d2e0e38ec040d013a125a",
   "sha256": "1yf21gm4ziplmgx8yn7jqq45mwfiindbrman7fc5b9ifq78x9ryn"
  },
  "stable": {
   "version": [
    1,
    1,
    1
   ],
   "commit": "beb22e85f6073a930f7338a78bd186e3090abdd7",
   "sha256": "1dhljrh44dsnixd8hbb11k6dgap8r8n7jknhfy2afdzq889fih74"
  }
 },
```
I see that the commit is present in emacs-overlay, but in unstable [sic] 2021 version.

**Comment by RafalBabinicz** [comment]
FWIW tree-sitter fails in similar way
```
error: Cannot find Git revision '4ef246db3e4ff99f672fe5e4b416c890f885c09e' in ref 'master' of repository 'https://codeberg.org/FelipeLema/tree-sitter-indent.el.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```

```json
{
  "ename": "tree-sitter-indent",
  "commit": "962f7c87d0630399ea388f25ec5792fa2f2b4489",
  "sha256": "0jm81c257mm7pxa2jhcxwy8ivwby4mixsiqsybsyhw3fz5dzq88a",
  "fetcher": "codeberg",
  "repo": "FelipeLema/tree-sitter-indent.el",
  "unstable": {
   "version": [
    20220411,
    1439
   ],
   "deps": [
    "seq",
    "tree-sitter"
   ],
   "commit": "4ef246db3e4ff99f672fe5e4b416c890f885c09e",
   "sha256": "0hs8fiwa5idhfxiskdp9k37ciqy32ll08fmf50y3bvrh6512dd66"
  },
  "stable": {
   "version": [
    0,
    3
   ],
   "deps": [
    "seq",
    "tree-sitter"
   ],
   "commit": "831a48571ccf14b8a8c607504a6e8e9263ff6dd4",
   "sha256": "1dfmlmmf13qzzfpmpc6lgwjhz8hnz5ys2fw4w3rrz6swfaa2vr53"
  }
 },
```

I've updated nixos unstable today and also enabled those two modules (and many more) so need to bisect whether that's new behavior, misconfiguration, or a bug.

PS The rest of my unstraightened config works without issues, and installs correctly after I omit above modules (zen and tree-sitter).

**Comment by marienz** [comment]
> According to readme I should try to pin emacs-overlay to be closer to doomemacs

Shouldn't really matter here. In general, I'd suggest leaving the emacs-overlay and doomemacs inputs of this flake alone (that'll give you the latest combination of both that CI can build).

But in this case, Doom pins mixed-pitch to 519e05f74825abf04b7d2e0e38ec040d013a125a (the rev in your error message), and has for a while (see https://github.com/doomemacs/doomemacs/blame/master/modules/ui/zen/packages.el): looks like that package hasn't been changing.

...which makes it weird it does not fetch. https://gitlab.com/jabranham/mixed-pitch is still there, and I cannot reproduce your fetch failure locally using Nix 2.24.10 (from NixOS 24.11). (Nix is fetching into ~/.cache/nix/gitv3/14vzjbgpp44bjpzlcl0pi12nyc0bmvwypr0hjfrjxz3hcpxabb7s, which it successfully re-fetches if I remove it and rebuild.)

Which version of Nix are you on, and does this reproduce both with and without `experimentalFetchTree = true` set (see README.md)? (That shouldn't make much of a difference with GitLab, since there's no dedicated fetcher for it, but might as well try both ways...).

Does a manual `git clone https://gitlab.com/jabranham/mixed-pitch.git` work?

The only thing that stands out is these are both hosts (codeberg.org and gitlab.com) for which we're not using a dedicated (non-Git) fetcher with experimentalFetchTree enabled. So if you had that enabled all along, these might be some of the few packages that actually used Git to fetch...

**Comment by RafalBabinicz** [comment]
After changing `experimentalFetchTree` to false, I was able to install both modules.
With it set to true after that, both modules install correctly, too.

The thing I changed, besides above, was updating unstraightened to the latest version
```
/etc/nixos🔒 >  sudo nix flake update nix-doom-emacs-unstraightened
warning: updating lock file '/etc/nixos/flake.lock':
• Updated input 'nix-doom-emacs-unstraightened':
    'github:marienz/nix-doom-emacs-unstraightened/67130d18a136f0c6a0f0391ada98d98c8503285e?narHash=sha256-RBFKEjRPGKk0AtO3CaO3mVgc93AVrShrznzkc6kjw1Q%3D' (2024-12-22)
  → 'github:marienz/nix-doom-emacs-unstraightened/e8f34a8fe52498417245ee9afb97c4a314d7b71e?narHash=sha256-V3pKrgvNRior1dfuonwAdiiiZkMu/kjIjejLdeUNSRk%3D' (2024-12-23)
• Updated input 'nix-doom-emacs-unstraightened/emacs-overlay':
    'github:nix-community/emacs-overlay/6e615f2298f3738547ccfc9bd6cacee3b9a323e6?narHash=sha256-iG/p%2BqKkapHxZdlVoY4GE2eSB%2B4QicvWXCLCNfDS9QM%3D' (2024-12-22)
  → 'github:nix-community/emacs-overlay/fd87d27a2bd726ef4ea161ee43fc9b1738a6fdb3?narHash=sha256-gCEo23vrBi6BaiTS9VJCM1E07Rkqh5Xbg7IETz0lacI%3D' (2024-12-23)
```

I should have try to install tree-sitter and zen before setting `experimentalFetchTree` to false.
Maybe it correctly downloaded sources to my nix store from gitlab and codeberg and now `experimentalFetchTree = true;' does not complain anymore.

I will keep my eye on it for the next time.
Thank you for pointing out to check `experimentalFetchTree`. Cheers.

**Comment by marienz** [comment]
>  Maybe it correctly downloaded sources to my nix store from gitlab and codeberg and now `experimentalFetchTree = true;' does not complain anymore.

Not just to the store, these get cached to (by default) ~/.cache/nix/gitv3.

I don't see why experimentalFetchTree false would make it work (to the best of my recollection it should have no effect), but if it works, it works :) Let me know if you hit this again (especially if you figure out a way of reproducing it) and I'll have a closer look...
